name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: get version
              id: version
              uses: notiz-dev/github-action-json-property@release
              with: 
                path: 'settings.json'
                prop_path: 'version'
            - run: echo ${{steps.version.outputs.prop}} 

            - uses: softprops/action-gh-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                RELEASE_TAG: ${{ github.ref_name }}
            - run: |
                gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${RELEASE_TAGg#v}" \
                --generate-notes \
                'README'+ ${{steps.version.outputs.prop}} +'.md'